apiVersion: 1

datasources:
  # TimescaleDB (PostgreSQL) - Trading data
  - name: TimescaleDB
    uid: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: trading_system
    user: trading_user
    secureJsonData:
      password: your_secure_password_here
    jsonData:
      database: trading_system
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
    editable: true
    isDefault: true

  # Prometheus - Metrics
  - name: Prometheus
    uid: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      timeInterval: 15s
    editable: true
